### ISSUE TITLE
Dependency update seems to have broken Syncy

### ISSUE THREAD

**Issue by Jusas** [mrmlnc/syncy#2]
I just recently had to purge my node_modules directory and fetch all my gulp modules again. Here's the thing: I've explicitly set the version number ("syncy": "1.0.1") so it should pull the exactly same version once again but apparently there has been an update in one of its deps (globby?) that breaks syncy and my tasks started to fail.

The error I get:  
`TypeError: Object false has no method 'concat'`

at c:\myproject\node_modules\syncy\node_modules\globby\index.js:33:25
    at Array.forEach (native)
    at generateGlobTasks (c:\myproject\node_modules\syncy\node_modules\globby\index.js:21:11)
    at module.exports (c:\myproject\node_modules\syncy\node_modules\globby\index.js:42:18)
    at DestroyableTransform._flush (c:\myproject\node_modules\syncy\index.js:49:7)
    at DestroyableTransform.<anonymous> (c:\myproject\node_modules\syncy\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:92:17)
    at prefinish (c:\myproject\node_modules\syncy\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:465:12)
    at finishMaybe (c:\myproject\node_modules\syncy\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:473:7)
    at endWritable (c:\myproject\node_modules\syncy\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (c:\myproject\node_modules\syncy\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at Gulp.gulp.task.syncy.base (c:\myproject\Gulpfile.js:191:10)
    at module.exports (c:\myproject\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\myproject\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\myproject\node_modules\gulp\node_modules\orchestrator\index.js:214:10)

**Comment by mrmlnc** [comment]
Thank you for issue :muscle:

I have updated the dependencies and pointing specific versions.

Sorry for this problem :tada:
